# Generated by Django 5.1.1 on 2024-09-20 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0002_fooditem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('special_requirement', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_menu.fooditem')),
            ],
        ),
    ]
